const Images = {
  backgroundImage: require('../Assets/Images/MainBackGround.jpg'),
  BlurBackgroundImage: require('../Assets/Images/BlurBackground.png'),
  Arrow_Disabled: require('../Assets/Icons/Arrow_Disabled.png'),
  Arrow: require('../Assets/Icons/Arrow.png'),
  logoVIB: require('../Assets/Images/logoVIB.png'),
  ic_voice_home: require('../Assets/Icons/ic_voice_home.png'),
  Card: require('../Assets/Images/Card.png'),
  Warning: require('../Assets/Icons/Warning.png'),
  Failed: require('../Assets/Icons/Failed.png'),
  Success: require('../Assets/Icons/Success.png'),
  ic_arrow_right: require('../Assets/Icons/ic_arrow_right.png'),
  ic_arrow_left: require('../Assets/Icons/ic_arrow_left.png'),
  HomeIcon: require('../Assets/Icons/Home.png'),
  HomeIconOutline: require('../Assets/Icons/Home_Outline.png'),
  ProfileIcon: require('../Assets/Icons/Profile.png'),
  ProfileIconOutline: require('../Assets/Icons/Profile_Outline.png'),
  PlusIcon: require('../Assets/Icons/Plus.png'),
  CloseIcon: require('../Assets/Icons/Close.png'),
  PayeeIcon: require('../Assets/Icons/Payee.png'),
  NFCIcon: require('../Assets/Icons/NFC.png'),
  TransferIcon: require('../Assets/Icons/Transfer.png'),
  LogoutIcon: require('../Assets/Icons/Logout.png'),
  HistoryIcon: require('../Assets/Icons/History.png'),
  ic_success: require('../Assets/Icons/ic_success.png'),
  NotiIcon: require('../Assets/Icons/Noti.png'),
  SettingIcon: require('../Assets/Icons/Setting.png'),
  VoiceIcon: require('../Assets/Icons/Voice.png'),
  MasterCardIcon: require('../Assets/Icons/MasterCard.png'),
  VoiceLargeIcon: require('../Assets/Icons/Voice_Large.png'),
  VoiceWaveIcon: require('../Assets/Icons/VoiceWave.png'),
};

export {Images};
