export const CONSTANTS = {
  TOKEN: 'TOKEN',
  PROFILE_ME: 'PROFILE_ME',
  VOICE_ASSISTANT: 'VOICE_ASSISTANT',
};

export const PAYMENT_FORM = {
  BANK_NAME: 'BANK_NAME',
  PAYEE_BANK_NO: 'BANK_NO',
  PAYEE_NAME: 'PAYEE_NAME',
  AMOUNT_PAYMENT: 'AMOUNT_PAYMENT',
  TRANSACTION_NOTE: 'TRANSACTION_NOTE',
};
